import React from "react";

export default function HowItWorks() {
  return (
    <div className="page-container">
      <h1 className="triage-meaning" style={{ fontSize: "var(--font-size-2xl)", fontWeight: 700 }}>
        How AIRA Works
      </h1>

      <p className="page-intro">
        AIRA is a deterministic clinical guideline navigator designed to make authoritative Indian government health guidelines accessible to adults and health workers.
      </p>

      <section className="step-card">
        <div className="step-number">STEP 1</div>
        <h2 className="step-title">Deterministic Safety Gate</h2>
        <p className="step-description">
          Before any language model is called, your query passes through deterministic Python safety rules. Any mention of life-threatening red flags, severe trauma, poisoning, or mental health crisis triggers an immediate static emergency response with helplines.
        </p>
      </section>

      <section className="step-card">
        <div className="step-number">STEP 2</div>
        <h2 className="step-title">Government Guideline Retrieval</h2>
        <p className="step-description">
          AIRA queries curated clinical guidelines published by the Indian Council of Medical Research (ICMR) and the Ministry of Health and Family Welfare (MOHFW). Relevant chunks are retrieved using hybrid BM25 keyword search and semantic vector embeddings.
        </p>
      </section>

      <section className="step-card">
        <div className="step-number">STEP 3</div>
        <h2 className="step-title">Rule-Enforced Triage Determination</h2>
        <p className="step-description">
          The triage urgency level (Emergency, See Doctor, Self Care, or Unknown) is decided entirely by a deterministic clinical rule table. The AI model is strictly prohibited from setting or changing the triage level.
        </p>
      </section>

      <section className="step-card">
        <div className="step-number">STEP 4</div>
        <h2 className="step-title">Strict Fact Verification and Extractive Fallback</h2>
        <p className="step-description">
          Every statement generated by the model must cite a verified guideline passage. Prohibited dosing, unsupported diagnostic claims, or ungrounded statements are rejected by output validators and replaced with verbatim excerpts directly from the source guidelines.
        </p>
      </section>

      <section className="step-card">
        <div className="step-number">STEP 5</div>
        <h2 className="step-title">Privacy and Statelessness</h2>
        <p className="step-description">
          AIRA does not store your query, does not create patient records, and does not write personal data to server logs.
        </p>
      </section>
    </div>
  );
}
