"""Output validators, citation builder, and extractive fallback for AIRA answer generation."""

import re
from collections.abc import Sequence
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from app.config import Settings
from app.config import settings as default_settings
from app.core.text import normalize
from app.data.corpus_loader import to_corpus_condition_id, to_profile_condition_id
from app.data.models import GuidelineChunk

# Allowed drug names from the clinical safety protocol
ALLOWED_DRUG_NAMES: frozenset[str] = frozenset(
    {
        "paracetamol",
        "ibuprofen",
        "aspirin",
        "nsaid",
        "nsaids",
        "antihistamine",
        "antihistamines",
        "petroleum jelly",
        "liquid paraffin",
    }
)

# Prohibited dosing regex patterns
DOSING_PATTERNS = [
    re.compile(r"\b\d+\s*(?:mg|mcg|iu)\b", re.IGNORECASE),
    re.compile(r"\b\d+\s*g\b", re.IGNORECASE),
    re.compile(
        r"\b(?:tablet|tablets|capsule|capsules|syrup|syrups|injection|injections|"
        r"twice daily|three times|bd|tds|qid|od)\b",
        re.IGNORECASE,
    ),
]

VOLUME_PATTERN = re.compile(
    r"\b\d+\s*(?:ml|litre|litres|liter|liters|glass|glasses)\b", re.IGNORECASE
)
ALLOWED_VOLUME_CONTEXTS = re.compile(
    r"\b(?:ors|water|fluid|fluids|salt|salts|liquid|drink|beverage)\b", re.IGNORECASE
)

# Prohibited diagnosis phrasing patterns
DIAGNOSIS_PATTERNS = [
    re.compile(r"\byou\s+have\b", re.IGNORECASE),
    re.compile(r"\byou\s+probably\s+have\b", re.IGNORECASE),
    re.compile(r"\byou\s+are\s+suffering\s+from\b", re.IGNORECASE),
    re.compile(r"\bthis\s+is\s+a\s+case\s+of\b", re.IGNORECASE),
    re.compile(r"\bdiagnosis\b", re.IGNORECASE),
    re.compile(r"\bdiagnosed\s+with\b", re.IGNORECASE),
]

# Emoji detection pattern
EMOJI_PATTERN = re.compile(
    r"[\U00010000-\U0010ffff"
    r"\u2600-\u27bf"
    r"\u2300-\u23ff"
    r"\u2b50\u2b55\u200d\ufe0f]"
)

# Stopwords for groundedness calculation
STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "in",
        "on",
        "at",
        "is",
        "are",
        "was",
        "were",
        "to",
        "of",
        "for",
        "with",
        "by",
        "and",
        "or",
        "but",
        "so",
        "if",
        "it",
        "this",
        "that",
        "be",
        "as",
        "from",
        "your",
        "you",
    }
)


def load_drug_lexicon(lexicon_path: Path | None = None) -> list[str]:
    """Load list of known drug names from lexicon file."""
    path = lexicon_path or (
        Path(__file__).resolve().parent.parent.parent / "data" / "lexicon" / "drug_lexicon.txt"
    )
    if not path.exists():
        return []
    drugs: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            clean = line.strip().lower()
            if clean and not clean.startswith("#") and clean not in ALLOWED_DRUG_NAMES:
                drugs.append(clean)
    return sorted(drugs, key=len, reverse=True)


class Claim(BaseModel):
    """A single factual claim with cited passage IDs."""

    text: str = Field(..., max_length=220)
    passage_ids: list[int] = Field(..., min_length=1)


class Draft(BaseModel):
    """Raw structured output generated by the language model."""

    guidelines_say: list[Claim] = Field(default_factory=list, max_length=4)
    do_now: list[Claim] = Field(default_factory=list, max_length=4)


class Citation(BaseModel):
    """Deduplicated citation source for a validated answer."""

    id: int
    title: str
    publisher: str
    year: str
    page: int | None = None
    url: str


class ValidatedClaim(BaseModel):
    """A verified claim carrying citation references."""

    text: str
    citation_ids: list[int]


class GeneratedAnswer(BaseModel):
    """Final answer delivered to the user with structured claims and citations."""

    guidelines_say: list[ValidatedClaim]
    do_now: list[ValidatedClaim]
    citations: list[Citation]
    mode: Literal["model", "extractive"]
    dropped_claims: int
    llm_error: str | None = None


def get_content_tokens(text: str) -> list[str]:
    """Extract normalized content tokens with stopwords removed."""
    norm = normalize(text)
    clean = norm.replace("|", " ")
    return [tok for tok in clean.split() if tok not in STOPWORDS and len(tok) > 1]


def check_forbidden_content(
    claim_text: str,
    cited_passage_text: str,
    drug_lexicon: list[str],
) -> tuple[bool, str]:
    """Check claim for dosing, forbidden drugs, diagnosis phrasing, em dashes, and emojis.

    Returns (is_valid, rejection_reason).
    """
    # 1. Em dash check
    if "\u2014" in claim_text or "\\u2014" in claim_text:
        return False, "Contains em dash"

    # 2. Emoji check
    if EMOJI_PATTERN.search(claim_text):
        return False, "Contains emoji"

    # 3. Diagnosis phrasing check
    for pat in DIAGNOSIS_PATTERNS:
        if pat.search(claim_text):
            return False, f"Contains diagnosis phrasing '{pat.pattern}'"

    # 4. Dosing check
    for pat in DOSING_PATTERNS:
        match = pat.search(claim_text)
        if match:
            return False, f"Contains prohibited dosing pattern '{match.group(0)}'"

    vol_match = VOLUME_PATTERN.search(claim_text)
    if vol_match and not ALLOWED_VOLUME_CONTEXTS.search(claim_text):
        return False, f"Contains volume '{vol_match.group(0)}' without allowed fluid context"

    # 5. Drug name check
    claim_lower = claim_text.lower()
    passage_lower = cited_passage_text.lower()
    for drug in drug_lexicon:
        drug_pattern = r"\b" + re.escape(drug) + r"\b"
        if re.search(drug_pattern, claim_lower, re.IGNORECASE) and not re.search(
            drug_pattern, passage_lower, re.IGNORECASE
        ):
            return False, f"Mentions ungrounded drug name '{drug}'"

    return True, ""


def check_groundedness(
    claim_text: str,
    cited_passage_text: str,
    threshold: float,
) -> tuple[bool, float]:
    """Compute token overlap between claim and cited passages.

    Returns (is_grounded, score).
    """
    claim_tokens = get_content_tokens(claim_text)
    if not claim_tokens:
        return False, 0.0

    passage_tokens = set(get_content_tokens(cited_passage_text))
    overlap = sum(1 for tok in claim_tokens if tok in passage_tokens)
    score = overlap / len(claim_tokens)

    return score >= threshold, score


def build_citations_and_claims(
    raw_claims: list[Claim],
    chunks: Sequence[GuidelineChunk],
) -> tuple[list[ValidatedClaim], list[Citation]]:
    """Build deduplicated citations and map 1-based passage IDs to citation IDs."""
    # Key: (title, page) -> (Citation, citation_id)
    citation_map: dict[tuple[str, int | None], Citation] = {}
    passage_to_citation_id: dict[int, int] = {}
    citation_counter = 1

    # First pass: establish citations for cited chunks
    for claim in raw_claims:
        for p_id in claim.passage_ids:
            if p_id not in passage_to_citation_id and 1 <= p_id <= len(chunks):
                chunk = chunks[p_id - 1]
                key = (chunk.source_title, chunk.page)
                if key not in citation_map:
                    cit = Citation(
                        id=citation_counter,
                        title=chunk.source_title,
                        publisher=chunk.source_publisher,
                        year=str(chunk.source_year),
                        page=chunk.page,
                        url=chunk.source_url,
                    )
                    citation_map[key] = cit
                    passage_to_citation_id[p_id] = citation_counter
                    citation_counter += 1
                else:
                    passage_to_citation_id[p_id] = citation_map[key].id

    # Second pass: construct validated claims with citation IDs
    validated_claims: list[ValidatedClaim] = []
    for claim in raw_claims:
        cit_ids = sorted(
            list(
                {
                    passage_to_citation_id[p_id]
                    for p_id in claim.passage_ids
                    if p_id in passage_to_citation_id
                }
            )
        )
        if cit_ids:
            validated_claims.append(ValidatedClaim(text=claim.text.strip(), citation_ids=cit_ids))

    all_citations = sorted(citation_map.values(), key=lambda c: c.id)
    return validated_claims, all_citations


def extract_items_from_chunk(chunk: GuidelineChunk) -> list[str]:
    """Extract individual clinical guidance items or sentences from a chunk."""
    text = chunk.text
    if "Section:" in text:
        parts = text.split("Section:", 1)[1]
        body = parts.split(".", 1)[1].strip() if "." in parts else parts.strip()
    else:
        body = text.strip()

    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", body) if s.strip()]
    return sentences


def build_extractive_fallback(
    chunks: Sequence[GuidelineChunk],
    dropped_count: int = 0,
    triage_level: str | None = None,
    detected_conditions: Sequence[str] | None = None,
    all_chunks: Sequence[GuidelineChunk] | None = None,
    llm_error: str | None = None,
) -> GeneratedAnswer:
    """Construct level-appropriate verbatim guideline items without model generation.

    Strict rules:
    - Never show danger_signs or refer_urgently items under guidelines_say or do_now
      unless the level is EMERGENCY.
    - SELF_CARE: guidelines_say and do_now come from the self_care section of the
      detected condition (verbatim, up to 4 items in total, each with its citation).
    - SEE_DOCTOR: guidelines_say comes from the see_doctor section of the detected
      condition. do_now comes from the self_care section if the condition has one
      (home measures until seen), otherwise left empty.
    - EMERGENCY: guidelines_say comes from danger_signs / refer_urgently sections.
    - If no condition is detected or level is UNKNOWN: no passages are returned.
    """
    if triage_level == "UNKNOWN" or (
        detected_conditions is not None and len(detected_conditions) == 0
    ):
        return GeneratedAnswer(
            guidelines_say=[],
            do_now=[],
            citations=[],
            mode="extractive",
            dropped_claims=dropped_count,
            llm_error=llm_error,
        )

    # Chunk pool: prefer all_chunks if supplied, else fallback to chunks
    pool = list(all_chunks) if all_chunks is not None else list(chunks)
    if not pool:
        return GeneratedAnswer(
            guidelines_say=[],
            do_now=[],
            citations=[],
            mode="extractive",
            dropped_claims=dropped_count,
            llm_error=llm_error,
        )

    # Match chunks belonging to detected conditions
    if detected_conditions is not None:
        target_cids = set()
        for cid in detected_conditions:
            target_cids.add(cid)
            target_cids.add(to_corpus_condition_id(cid))
            target_cids.add(to_profile_condition_id(cid))

        cond_chunks = [ch for ch in pool if ch.condition_id in target_cids]
        if not cond_chunks:
            cond_chunks = list(chunks)
    else:
        cond_chunks = list(chunks)

    self_care_chunks = [ch for ch in cond_chunks if ch.section_type == "self_care"]
    see_doctor_chunks = [ch for ch in cond_chunks if ch.section_type == "see_doctor"]
    danger_chunks = [
        ch for ch in cond_chunks if ch.section_type in ("danger_signs", "refer_urgently")
    ]

    def collect_items(
        source_chunks: list[GuidelineChunk], limit: int
    ) -> list[tuple[str, GuidelineChunk]]:
        items: list[tuple[str, GuidelineChunk]] = []
        for ch in source_chunks:
            extracted = extract_items_from_chunk(ch)
            for itm in extracted:
                if len(itm) > 220:
                    itm = itm[:217] + "..."
                items.append((itm, ch))
                if len(items) >= limit:
                    return items
        return items

    guidelines_pairs: list[tuple[str, GuidelineChunk]] = []
    do_now_pairs: list[tuple[str, GuidelineChunk]] = []

    if triage_level == "SELF_CARE":
        # Up to 4 items in total from self_care section
        all_self_care = collect_items(self_care_chunks, limit=4)
        if len(all_self_care) >= 4:
            guidelines_pairs = all_self_care[0:2]
            do_now_pairs = all_self_care[2:4]
        elif len(all_self_care) == 3:
            guidelines_pairs = all_self_care[0:2]
            do_now_pairs = all_self_care[2:3]
        elif len(all_self_care) == 2:
            guidelines_pairs = all_self_care[0:1]
            do_now_pairs = all_self_care[1:2]
        elif len(all_self_care) == 1:
            guidelines_pairs = all_self_care[0:1]
            do_now_pairs = []
    elif triage_level == "SEE_DOCTOR":
        # What the guidelines say: see_doctor section (up to 4 items)
        guidelines_pairs = collect_items(see_doctor_chunks, limit=4)
        # What to do now: self_care section if available (up to 2 items)
        do_now_pairs = collect_items(self_care_chunks, limit=2)
    elif triage_level == "EMERGENCY":
        guidelines_pairs = collect_items(danger_chunks, limit=4)
        do_now_pairs = []
    else:
        # Fallback for generic/other: do not include danger signs
        guidelines_pairs = collect_items(
            see_doctor_chunks or self_care_chunks or cond_chunks, limit=4
        )
        do_now_pairs = []

    # Build citations and claims for guidelines_say and do_now
    citation_map: dict[tuple[str, int | None], Citation] = {}
    citation_counter = 1

    def make_claims(pairs: list[tuple[str, GuidelineChunk]]) -> list[ValidatedClaim]:
        nonlocal citation_counter
        claims_out: list[ValidatedClaim] = []
        for text_str, ch in pairs:
            key = (ch.source_title, ch.page)
            if key not in citation_map:
                cit = Citation(
                    id=citation_counter,
                    title=ch.source_title,
                    publisher=ch.source_publisher,
                    year=str(ch.source_year),
                    page=ch.page,
                    url=ch.source_url,
                )
                citation_map[key] = cit
                cit_id = citation_counter
                citation_counter += 1
            else:
                cit_id = citation_map[key].id
            claims_out.append(ValidatedClaim(text=text_str, citation_ids=[cit_id]))
        return claims_out

    g_claims = make_claims(guidelines_pairs)
    d_claims = make_claims(do_now_pairs)
    citations_list = sorted(citation_map.values(), key=lambda c: c.id)

    return GeneratedAnswer(
        guidelines_say=g_claims,
        do_now=d_claims,
        citations=citations_list,
        mode="extractive",
        dropped_claims=dropped_count,
        llm_error=llm_error,
    )


def validate_draft(
    draft: Draft | None,
    chunks: Sequence[GuidelineChunk],
    settings: Settings | None = None,
    drug_lexicon: list[str] | None = None,
    triage_level: str | None = None,
    detected_conditions: Sequence[str] | None = None,
    all_chunks: Sequence[GuidelineChunk] | None = None,
    llm_error: str | None = None,
) -> GeneratedAnswer:
    """Execute validation pipeline on drafted claims and build citations.

    Falls back to extractive answers if no valid claims survive.
    """
    app_settings = settings or default_settings
    lexicon = drug_lexicon if drug_lexicon is not None else load_drug_lexicon()
    chunk_list = list(chunks)
    valid_passage_ids = set(range(1, len(chunk_list) + 1))

    if not draft or not chunk_list:
        return build_extractive_fallback(
            chunk_list,
            dropped_count=0,
            triage_level=triage_level,
            detected_conditions=detected_conditions,
            all_chunks=all_chunks,
            llm_error=llm_error,
        )

    # Combine passage text lookup
    passage_text_map: dict[int, str] = {i + 1: chunk_list[i].text for i in range(len(chunk_list))}

    dropped_count = 0

    def validate_claim_list(claims: list[Claim], max_count: int) -> list[Claim]:
        nonlocal dropped_count
        surviving: list[Claim] = []

        for clm in claims:
            # 1. Length cap check
            if len(clm.text) > 220 or not clm.text.strip():
                dropped_count += 1
                continue

            # 2. Passage IDs validity
            if not clm.passage_ids or not all(pid in valid_passage_ids for pid in clm.passage_ids):
                dropped_count += 1
                continue

            # If triage level is not EMERGENCY, never show danger_signs or refer_urgently
            if triage_level != "EMERGENCY":
                cites_danger = any(
                    1 <= pid <= len(chunk_list)
                    and chunk_list[pid - 1].section_type in ("danger_signs", "refer_urgently")
                    for pid in clm.passage_ids
                )
                if cites_danger:
                    dropped_count += 1
                    continue

            # Collect text of all cited passages
            cited_texts = " ".join(passage_text_map[pid] for pid in clm.passage_ids)

            # 3. Groundedness token overlap
            is_grounded, _score = check_groundedness(
                clm.text, cited_texts, app_settings.groundedness_threshold
            )
            if not is_grounded:
                dropped_count += 1
                continue

            # 4. Forbidden content check
            is_clean, _reason = check_forbidden_content(clm.text, cited_texts, lexicon)
            if not is_clean:
                dropped_count += 1
                continue

            surviving.append(clm)
            if len(surviving) >= max_count:
                break

        return surviving

    valid_guidelines = validate_claim_list(draft.guidelines_say, max_count=4)
    valid_do_now = validate_claim_list(draft.do_now, max_count=4)

    total_valid = len(valid_guidelines) + len(valid_do_now)
    if total_valid == 0:
        # Fallback to extractive
        return build_extractive_fallback(
            chunk_list,
            dropped_count=dropped_count,
            triage_level=triage_level,
            detected_conditions=detected_conditions,
            all_chunks=all_chunks,
            llm_error=llm_error,
        )

    # Build citations across surviving claims
    all_surviving = valid_guidelines + valid_do_now
    _, citations = build_citations_and_claims(all_surviving, chunk_list)

    # Map claims with citations
    g_claims, _ = build_citations_and_claims(valid_guidelines, chunk_list)
    d_claims, _ = build_citations_and_claims(valid_do_now, chunk_list)

    return GeneratedAnswer(
        guidelines_say=g_claims,
        do_now=d_claims,
        citations=citations,
        mode="model",
        dropped_claims=dropped_count,
        llm_error=llm_error,
    )
