"""Output validators, citation builder, and extractive fallback for AIRA answer generation."""

import re
from collections.abc import Sequence
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from app.config import Settings
from app.config import settings as default_settings
from app.core.text import normalize
from app.data.models import GuidelineChunk

# Allowed drug names from the clinical safety protocol
ALLOWED_DRUG_NAMES: frozenset[str] = frozenset(
    {
        "paracetamol",
        "ibuprofen",
        "aspirin",
        "nsaid",
        "nsaids",
        "antihistamine",
        "antihistamines",
        "petroleum jelly",
        "liquid paraffin",
    }
)

# Prohibited dosing regex patterns
DOSING_PATTERNS = [
    re.compile(r"\b\d+\s*(?:mg|mcg|iu)\b", re.IGNORECASE),
    re.compile(r"\b\d+\s*g\b", re.IGNORECASE),
    re.compile(
        r"\b(?:tablet|tablets|capsule|capsules|syrup|syrups|injection|injections|"
        r"twice daily|three times|bd|tds|qid|od)\b",
        re.IGNORECASE,
    ),
]

VOLUME_PATTERN = re.compile(
    r"\b\d+\s*(?:ml|litre|litres|liter|liters|glass|glasses)\b", re.IGNORECASE
)
ALLOWED_VOLUME_CONTEXTS = re.compile(
    r"\b(?:ors|water|fluid|fluids|salt|salts|liquid|drink|beverage)\b", re.IGNORECASE
)

# Prohibited diagnosis phrasing patterns
DIAGNOSIS_PATTERNS = [
    re.compile(r"\byou\s+have\b", re.IGNORECASE),
    re.compile(r"\byou\s+probably\s+have\b", re.IGNORECASE),
    re.compile(r"\byou\s+are\s+suffering\s+from\b", re.IGNORECASE),
    re.compile(r"\bthis\s+is\s+a\s+case\s+of\b", re.IGNORECASE),
    re.compile(r"\bdiagnosis\b", re.IGNORECASE),
    re.compile(r"\bdiagnosed\s+with\b", re.IGNORECASE),
]

# Emoji detection pattern
EMOJI_PATTERN = re.compile(
    r"[\U00010000-\U0010ffff"
    r"\u2600-\u27bf"
    r"\u2300-\u23ff"
    r"\u2b50\u2b55\u200d\ufe0f]"
)

# Stopwords for groundedness calculation
STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "in",
        "on",
        "at",
        "is",
        "are",
        "was",
        "were",
        "to",
        "of",
        "for",
        "with",
        "by",
        "and",
        "or",
        "but",
        "so",
        "if",
        "it",
        "this",
        "that",
        "be",
        "as",
        "from",
        "your",
        "you",
    }
)


def load_drug_lexicon(lexicon_path: Path | None = None) -> list[str]:
    """Load list of known drug names from lexicon file."""
    path = lexicon_path or (
        Path(__file__).resolve().parent.parent.parent / "data" / "lexicon" / "drug_lexicon.txt"
    )
    if not path.exists():
        return []
    drugs: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            clean = line.strip().lower()
            if clean and not clean.startswith("#") and clean not in ALLOWED_DRUG_NAMES:
                drugs.append(clean)
    return sorted(drugs, key=len, reverse=True)


class Claim(BaseModel):
    """A single factual claim with cited passage IDs."""

    text: str = Field(..., max_length=220)
    passage_ids: list[int] = Field(..., min_length=1)


class Draft(BaseModel):
    """Raw structured output generated by the language model."""

    guidelines_say: list[Claim] = Field(default_factory=list, max_length=4)
    do_now: list[Claim] = Field(default_factory=list, max_length=4)


class Citation(BaseModel):
    """Deduplicated citation source for a validated answer."""

    id: int
    title: str
    publisher: str
    year: str
    page: int | None = None
    url: str


class ValidatedClaim(BaseModel):
    """A verified claim carrying citation references."""

    text: str
    citation_ids: list[int]


class GeneratedAnswer(BaseModel):
    """Final answer delivered to the user with structured claims and citations."""

    guidelines_say: list[ValidatedClaim]
    do_now: list[ValidatedClaim]
    citations: list[Citation]
    mode: Literal["model", "extractive"]
    dropped_claims: int


def get_content_tokens(text: str) -> list[str]:
    """Extract normalized content tokens with stopwords removed."""
    norm = normalize(text)
    clean = norm.replace("|", " ")
    return [tok for tok in clean.split() if tok not in STOPWORDS and len(tok) > 1]


def check_forbidden_content(
    claim_text: str,
    cited_passage_text: str,
    drug_lexicon: list[str],
) -> tuple[bool, str]:
    """Check claim for dosing, forbidden drugs, diagnosis phrasing, em dashes, and emojis.

    Returns (is_valid, rejection_reason).
    """
    # 1. Em dash check
    if "\u2014" in claim_text or "\\u2014" in claim_text:
        return False, "Contains em dash"

    # 2. Emoji check
    if EMOJI_PATTERN.search(claim_text):
        return False, "Contains emoji"

    # 3. Diagnosis phrasing check
    for pat in DIAGNOSIS_PATTERNS:
        if pat.search(claim_text):
            return False, f"Contains diagnosis phrasing '{pat.pattern}'"

    # 4. Dosing check
    for pat in DOSING_PATTERNS:
        match = pat.search(claim_text)
        if match:
            return False, f"Contains prohibited dosing pattern '{match.group(0)}'"

    vol_match = VOLUME_PATTERN.search(claim_text)
    if vol_match and not ALLOWED_VOLUME_CONTEXTS.search(claim_text):
        return False, f"Contains volume '{vol_match.group(0)}' without allowed fluid context"

    # 5. Drug name check
    claim_lower = claim_text.lower()
    passage_lower = cited_passage_text.lower()
    for drug in drug_lexicon:
        drug_pattern = r"\b" + re.escape(drug) + r"\b"
        if re.search(drug_pattern, claim_lower, re.IGNORECASE) and not re.search(
            drug_pattern, passage_lower, re.IGNORECASE
        ):
            return False, f"Mentions ungrounded drug name '{drug}'"

    return True, ""


def check_groundedness(
    claim_text: str,
    cited_passage_text: str,
    threshold: float,
) -> tuple[bool, float]:
    """Compute token overlap between claim and cited passages.

    Returns (is_grounded, score).
    """
    claim_tokens = get_content_tokens(claim_text)
    if not claim_tokens:
        return False, 0.0

    passage_tokens = set(get_content_tokens(cited_passage_text))
    overlap = sum(1 for tok in claim_tokens if tok in passage_tokens)
    score = overlap / len(claim_tokens)

    return score >= threshold, score


def build_citations_and_claims(
    raw_claims: list[Claim],
    chunks: Sequence[GuidelineChunk],
) -> tuple[list[ValidatedClaim], list[Citation]]:
    """Build deduplicated citations and map 1-based passage IDs to citation IDs."""
    # Key: (title, page) -> (Citation, citation_id)
    citation_map: dict[tuple[str, int | None], Citation] = {}
    passage_to_citation_id: dict[int, int] = {}
    citation_counter = 1

    # First pass: establish citations for cited chunks
    for claim in raw_claims:
        for p_id in claim.passage_ids:
            if p_id not in passage_to_citation_id and 1 <= p_id <= len(chunks):
                chunk = chunks[p_id - 1]
                key = (chunk.source_title, chunk.page)
                if key not in citation_map:
                    cit = Citation(
                        id=citation_counter,
                        title=chunk.source_title,
                        publisher=chunk.source_publisher,
                        year=str(chunk.source_year),
                        page=chunk.page,
                        url=chunk.source_url,
                    )
                    citation_map[key] = cit
                    passage_to_citation_id[p_id] = citation_counter
                    citation_counter += 1
                else:
                    passage_to_citation_id[p_id] = citation_map[key].id

    # Second pass: construct validated claims with citation IDs
    validated_claims: list[ValidatedClaim] = []
    for claim in raw_claims:
        cit_ids = sorted(
            list(
                {
                    passage_to_citation_id[p_id]
                    for p_id in claim.passage_ids
                    if p_id in passage_to_citation_id
                }
            )
        )
        if cit_ids:
            validated_claims.append(ValidatedClaim(text=claim.text.strip(), citation_ids=cit_ids))

    all_citations = sorted(citation_map.values(), key=lambda c: c.id)
    return validated_claims, all_citations


def build_extractive_fallback(
    chunks: Sequence[GuidelineChunk],
    dropped_count: int = 0,
) -> GeneratedAnswer:
    """Construct verbatim guideline items from top retrieved chunks without model generation."""
    if not chunks:
        return GeneratedAnswer(
            guidelines_say=[],
            do_now=[],
            citations=[],
            mode="extractive",
            dropped_claims=dropped_count,
        )

    fallback_chunks = list(chunks[:2])
    claims_raw: list[Claim] = []

    # Extract sentences/items verbatim
    for idx, ch in enumerate(fallback_chunks, start=1):
        text = ch.text
        # Strip header prefix if present
        if "Section:" in text:
            parts = text.split("Section:", 1)[1]
            body = parts.split(".", 1)[1].strip() if "." in parts else parts.strip()
        else:
            body = text.strip()

        # Split into individual sentences
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", body) if s.strip()]
        for s in sentences:
            if len(s) > 220:
                s = s[:217] + "..."
            if len(claims_raw) < 4:
                claims_raw.append(Claim(text=s, passage_ids=[idx]))

    validated_claims, citations = build_citations_and_claims(claims_raw, fallback_chunks)

    return GeneratedAnswer(
        guidelines_say=validated_claims,
        do_now=[],
        citations=citations,
        mode="extractive",
        dropped_claims=dropped_count,
    )


def validate_draft(
    draft: Draft | None,
    chunks: Sequence[GuidelineChunk],
    settings: Settings | None = None,
    drug_lexicon: list[str] | None = None,
) -> GeneratedAnswer:
    """Execute validation pipeline on drafted claims and build citations.

    Falls back to extractive answers if no valid claims survive.
    """
    app_settings = settings or default_settings
    lexicon = drug_lexicon if drug_lexicon is not None else load_drug_lexicon()
    chunk_list = list(chunks)
    valid_passage_ids = set(range(1, len(chunk_list) + 1))

    if not draft or not chunk_list:
        return build_extractive_fallback(chunk_list, dropped_count=0)

    # Combine passage text lookup
    passage_text_map: dict[int, str] = {i + 1: chunk_list[i].text for i in range(len(chunk_list))}

    dropped_count = 0

    def validate_claim_list(claims: list[Claim], max_count: int) -> list[Claim]:
        nonlocal dropped_count
        surviving: list[Claim] = []

        for clm in claims:
            # 1. Length cap check
            if len(clm.text) > 220 or not clm.text.strip():
                dropped_count += 1
                continue

            # 2. Passage IDs validity
            if not clm.passage_ids or not all(pid in valid_passage_ids for pid in clm.passage_ids):
                dropped_count += 1
                continue

            # Collect text of all cited passages
            cited_texts = " ".join(passage_text_map[pid] for pid in clm.passage_ids)

            # 3. Groundedness token overlap
            is_grounded, _score = check_groundedness(
                clm.text, cited_texts, app_settings.groundedness_threshold
            )
            if not is_grounded:
                dropped_count += 1
                continue

            # 4. Forbidden content check
            is_clean, _reason = check_forbidden_content(clm.text, cited_texts, lexicon)
            if not is_clean:
                dropped_count += 1
                continue

            surviving.append(clm)
            if len(surviving) >= max_count:
                break

        return surviving

    valid_guidelines = validate_claim_list(draft.guidelines_say, max_count=4)
    valid_do_now = validate_claim_list(draft.do_now, max_count=4)

    total_valid = len(valid_guidelines) + len(valid_do_now)
    if total_valid == 0:
        # Fallback to extractive
        return build_extractive_fallback(chunk_list, dropped_count=dropped_count)

    # Build citations across surviving claims
    all_surviving = valid_guidelines + valid_do_now
    _, citations = build_citations_and_claims(all_surviving, chunk_list)

    # Map claims with citations
    g_claims, _ = build_citations_and_claims(valid_guidelines, chunk_list)
    d_claims, _ = build_citations_and_claims(valid_do_now, chunk_list)

    return GeneratedAnswer(
        guidelines_say=g_claims,
        do_now=d_claims,
        citations=citations,
        mode="model",
        dropped_claims=dropped_count,
    )
